name: ve.impress
channels:
  - pytorch
  - conda-forge
  - https://conda.rosettacommons.org
  - defaults
dependencies:
  - python=3.9
  - jax=0.3.25
  - biopandas
  - radical.pilot
  - cudatoolkit=11.3
  - pandas
  - pyrosetta
  - pytorch
  - torchaudio
  - torchvision
